repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: ''  # Specify a specific version/tag/commit or leave empty for the latest version
  hooks:
    - id: autopep8
      exclude: '^$'  # Specify files or patterns to exclude, '^$' excludes nothing (all files will be checked)
      args: [--verbose]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: [--ignore=E501]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake